name: 'test'

on: workflow_call

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      minecraft-versions: ${{ steps.get-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      
      - name: get minecraft versions
        id: get-versions
        run: |
          # Extract versions from version_properties directory
          versions=$(find version_properties/ -name "*.properties" -exec basename {} .properties \; | jq -R -s -c 'split("\n")[:-1]')
          echo "versions=$versions" >> $GITHUB_OUTPUT
          echo "Found versions: $versions"

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft-version: ${{ fromJson(needs.generate-matrix.outputs.minecraft-versions) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: GameTest for Minecraft ${{ matrix.minecraft-version }}
        run: ./gradlew runGameTest -PmcVer=${{ matrix.minecraft-version }}

      - name: Unit Tests for Minecraft ${{ matrix.minecraft-version }}
        run: ./gradlew test -PmcVer=${{ matrix.minecraft-version }}

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.minecraft-version }}
          path: |
            **/build/reports/
            **/build/test-results/